-- Continuation — see 20260730050000_seed_real_products.sql header for the
-- price/image/score rationale. Additional real, currently-existing models
-- for categories that had room to grow further toward 20.

insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values

-- window-cleaners (+3, now 12)
('ecovacs-winbot-950','Ecovacs Winbot 950','Ecovacs',(select id from categories where slug='window-cleaners'),7.9,'דגם ותיק וידוע של Ecovacs לניקוי חלונות, עדיין נמכר ופופולרי בזכות מחיר יציב לאורך זמן.',ARRAY['מחיר יציב ונגיש לאורך שנים','אמינות מוכחת לאורך זמן'],ARRAY['ללא ניווט חכם מתקדם כמו הדגמים החדשים'],'{"היצמדות":"שאיבת ואקום"}','published','אופציה מוכחת ויציבה למי שלא צריך את הטכנולוגיה החדשה ביותר.',ARRAY['חלונות ביתיים רגילים'],ARRAY['קירות זכוכית גדולים ומורכבים'],ARRAY['established'],ARRAY['window-cleaners']),
('alfawise-s60-pro','Alfawise S60 Pro','Alfawise',(select id from categories where slug='window-cleaners'),7.3,'שדרוג לדגם S60 הבסיסי עם סוללת גיבוי משופרת למקרה של הפסקת חשמל.',ARRAY['סוללת גיבוי משופרת לבטיחות','מחיר עדיין נגיש יחסית'],ARRAY['ביצועי ניווט בסיסיים'],'{"היצמדות":"שאיבת ואקום","בטיחות":"סוללת גיבוי משופרת"}','published','שדרוג קטן אך משמעותי לבטיחות ביחס לדגם הבסיסי, במחיר עדיין נגיש.',ARRAY['חלונות ביתיים בקומה גבוהה עם תקציב מוגבל'],ARRAY['קירות זכוכית מסחריים'],ARRAY['budget','safety'],ARRAY['window-cleaners']),
('hobot-268','Hobot 268','Hobot',(select id from categories where slug='window-cleaners'),7.6,'דגם ביניים נוסף בקו Hobot, בין הדגם הבסיסי 298 לדגל 388/Legee.',ARRAY['איזון טוב בין מחיר ליכולת ניקוי','מותג מוכר ואמין'],ARRAY['ללא מיפוי חכם לפני ניקוי כמו הדגל'],'{"היצמדות":"שאיבת ואקום"}','published','עוד נקודת איזון בקו Hobot למי שלא בטוח בין הדגמים.',ARRAY['חלונות בגודל בינוני'],ARRAY['קירות זכוכית ענקיים'],ARRAY['value'],ARRAY['window-cleaners']),

-- pool-cleaners (+3, now 16)
('dolphin-nautilus-cc-plus','Dolphin Nautilus CC Plus','Maytronics',(select id from categories where slug='pool-cleaners'),8.5,'אחד הדגמים הנמכרים ביותר בעולם של מייטרוניקס, ממוקד קרקעית ודפנות בפשטות ואמינות.',ARRAY['אחד המוצרים הנמכרים ביותר בעולם בקטגוריה','חברה ישראלית עם שירות מקיף'],ARRAY['ללא ניקוי קו מים כמו הדגמים הפרימיום'],'{"ניקוי":"קרקעית ודפנות"}','published','נקודת איזון מוכחת עולמית בין מחיר לאמינות בקו Dolphin.',ARRAY['בריכות ביתיות סטנדרטיות'],ARRAY['בריכות עם דרישות ניקוי קו מים'],ARRAY['israeli','popular'],ARRAY['pool-cleaners']),
('polaris-9450-sport','Polaris 9450 Sport','Polaris',(select id from categories where slug='pool-cleaners'),8.2,'דגם ביניים בקו Polaris עם הנעת 4WD ומחיר נגיש יותר מדגם ה-9550.',ARRAY['הנעת 4WD','מחיר נגיש יותר מהדגם המתקדם'],ARRAY['ניקוי קו מים מוגבל'],'{"הנעה":"4WD","ניקוי":"קרקעית ודפנות"}','published','רוב יתרונות ה-9550 במחיר נגיש יותר.',ARRAY['בריכות עם דפנות משופעות בתקציב בינוני'],ARRAY['בריכות הדורשות ניקוי קו מים מלא'],ARRAY['value'],ARRAY['pool-cleaners']),
('aiper-scuba-s1','Aiper Scuba S1','Aiper',(select id from categories where slug='pool-cleaners'),7.9,'דגם כניסה אלחוטי של Aiper, נגיש יותר מדגמי ה-Pro וה-X1.',ARRAY['מחיר נגיש לקטגוריית האלחוטיים','ללא כבל כלל'],ARRAY['זמן ריצה קצר יותר מהדגמים המתקדמים'],'{"חשמל":"סוללה נטענת","ניקוי":"קרקעית בעיקר"}','published','נקודת כניסה תקציבית לעולם רובוטי הבריכה האלחוטיים.',ARRAY['בריכות קטנות-בינוניות בתקציב מוגבל'],ARRAY['בריכות גדולות שדורשות ריצה ארוכה'],ARRAY['budget','cordless'],ARRAY['pool-cleaners']),

-- lawn-mowers (+2, now 17)
('husqvarna-automower-435x-awd','Husqvarna Automower 435X AWD','Husqvarna',(select id from categories where slug='lawn-mowers'),8.8,'דגם AWD בקו Automower, מתמודד עם שיפועים ותנאי שטח מאתגרים במיוחד.',ARRAY['הנעת AWD לשיפועים תלולים','ניווט GPS מדויק'],ARRAY['מחיר גבוה'],'{"ניווט":"GPS","הנעה":"AWD (כל הגלגלים)"}','published','הבחירה של Husqvarna לחצרות עם שיפועים משמעותיים.',ARRAY['חצרות עם שיפועים תלולים'],ARRAY['חצרות שטוחות פשוטות'],ARRAY['awd','premium'],ARRAY['lawn-mowers']),
('worx-landroid-m700-plus','Worx Landroid M700 Plus','Worx',(select id from categories where slug='lawn-mowers'),8.0,'דגם עדכני יותר בקו M של Worx, עם שיפורי ניווט וחיתוך לעומת דגמי M500 הוותיקים.',ARRAY['שיפורי ניווט לעומת הדור הקודם','מחיר עדיין תחרותי'],ARRAY['דורש כבל היקפי'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-700 מ״ר"}','published','גרסה מעודכנת לדגמי M הוותיקים של Worx, איזון טוב בין מחיר לביצועים.',ARRAY['חצרות ביתיות בגודל בינוני'],ARRAY['מי שרוצה להימנע מכבל היקפי'],ARRAY['value'],ARRAY['lawn-mowers']),

-- mops (+3, now 20)
('dreame-x30-ultra','Dreame X30 Ultra','Dreame',(select id from categories where slug='mops'),9.1,'דגם משולב מתקדם של Dreame עם דגש חזק על שטיפה, כולל זרוע מגב וניקוי מגב בחום.',ARRAY['זרוע מגב מתרוממת','ניקוי מגב בחום בתחנה','שאיבה חזקה'],ARRAY['מחיר גבוה'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת + ניקוי בחום"}','published','שטיפה ברמה גבוהה מאוד, חלופה ישירה לדגמי הדגל של Roborock.',ARRAY['בתים עם ריצוף קשיח נרחב ושטיחים'],ARRAY['תקציב מוגבל'],ARRAY['flagship','combo'],ARRAY['mops']),
('roborock-s7-maxv-ultra','Roborock S7 MaxV Ultra','Roborock',(select id from categories where slug='mops'),8.7,'הדור שקדם ל-S8, עדיין נמכר ומספק זרוע מגב מתרוממת ותחנה מלאה במחיר נמוך מהדגם הנוכחי.',ARRAY['זרוע מגב מתרוממת','תחנה מלאה','מחיר נמוך מהדור החדש'],ARRAY['שאיבה חלשה יחסית לדור S8'],'{"ניווט":"LiDAR + מצלמה","תחנה":"ריקון, שטיפה וייבוש"}','published','רוב היתרונות של קו ה-Ultra במחיר נמוך יותר, בזכות היותו דור קודם.',ARRAY['תקציב בינוני שרוצה זרוע מגב מתרוממת'],ARRAY['מי שרוצה את השאיבה החזקה ביותר'],ARRAY['value','combo'],ARRAY['mops']),
('ecovacs-deebot-x8-pro-omni','Ecovacs Deebot X8 Pro Omni','Ecovacs',(select id from categories where slug='mops'),8.4,'דגם עם זרוע מגב מתרוממת ומברשת ראשית שגם היא נעה הצידה מעל שטיחים.',ARRAY['גם מברשת וגם מגב נעים משטיחים','תחנה מלאה'],ARRAY['מחיר בקצה הגבוה של הקטגוריה'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת + מברשת נעה"}','published','פתרון מקיף לבתים עם שטיחים בצורות לא אחידות.',ARRAY['בתים עם שטיחים בצורות שונות'],ARRAY['תקציב מוגבל'],ARRAY['combo'],ARRAY['mops'])

on conflict (slug) do nothing;
