-- Real, currently-existing consumer robot models, with genuinely known
-- general specs and editorial pros/cons. Deliberately NOT including:
--   * price_from / offers — no live Israeli retail price feed exists in
--     this environment, and a wrong shekel figure on a commerce site is
--     worse than no figure. The existing UI already handles this
--     honestly: a null price shows "—", and a robot with zero offers
--     shows "עדיין לא נמכר בישראל" instead of a fabricated store link.
--   * hero_image — no verified real product photo URLs on hand; the
--     existing ProductImage component already falls back to a generic
--     placeholder when hero_image is null, so nothing breaks or looks
--     fake.
--   * score — this is the site's own editorial rating (see
--     /methodology), not a claimed manufacturer or aggregate figure, so
--     an editorial 1–10 here is legitimate, not fabricated data.
--
-- Counts per category reflect how many genuinely real, currently
-- existing consumer products exist in that space today — padded to 20
-- nowhere. Humanoids in particular barely have a real consumer market
-- yet, so that category is intentionally short.

-- ===================== robot-vacuums (20) =====================
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('roborock-s8-maxv-ultra','Roborock S8 MaxV Ultra','Roborock',(select id from categories where slug='robot-vacuums'),9.4,'הדגל של Roborock: זרועה מכנית שמרימה את מגב השטיפה מעל שטיחים, וריקון/שטיפה/ייבוש עצמאיים בתחנה.',ARRAY['זרוע מגב מתרוממת אוטומטית מעל שטיחים','תחנה עצמאית מלאה כולל ניקוי מגבים בחום','ניווט LiDAR מדויק עם זיהוי מכשולים בעל מצלמה'],ARRAY['תחנת העגינה גדולה ותופסת מקום','מחיר בקצה העליון של הקטגוריה'],'{"ניווט":"LiDAR + מצלמת RGB","תחנה":"ריקון, שטיפה וייבוש עצמי","שטיפה":"זרוע מגב מתרוממת (VibraRise)"}','published','הבחירה הבטוחה למי שרוצה את המערכת המשולבת הכי שלמה, כולל טיפול אוטומטי בשטיחים.',ARRAY['בתים עם שטיחים וריצוף מעורב','מי שרוצה תחזוקה מינימלית'],ARRAY['דירות קטנות בלי מקום לתחנה גדולה'],ARRAY['flagship','combo'],ARRAY['robot-vacuums']),
('roborock-s8-pro-ultra','Roborock S8 Pro Ultra','Roborock',(select id from categories where slug='robot-vacuums'),9.1,'קודמו של ה-MaxV Ultra, עם אותה תחנה מלאה ומגב מתרומם, בלי המצלמה המתקדמת לזיהוי חפצים.',ARRAY['תחנה עצמאית מלאה','זרוע מגב מתרוממת','מחיר נגיש יותר מהדגם המקסימלי'],ARRAY['זיהוי מכשולים פחות מדויק בלי המצלמה הנוספת'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש עצמי"}','published','תחנה מלאה במחיר סביר יותר, למי שמוכן לוותר על זיהוי החפצים המתקדם ביותר.',ARRAY['משפחות עם תקציב בינוני-גבוה'],ARRAY['בתים עם הרבה חפצים קטנים על הרצפה'],ARRAY['flagship','combo'],ARRAY['robot-vacuums']),
('roborock-qrevo-master','Roborock Qrevo Master','Roborock',(select id from categories where slug='robot-vacuums'),9.0,'קו המוצרים המקביל של Roborock, עם זרוע מגב וניקוי קצוות משופר בעזרת מברשת צד נשלפת.',ARRAY['מברשת צד נשלפת מגיעה טוב יותר לפינות','תחנה מלאה כולל ריקון ושטיפה','שאיבה חזקה מאוד'],ARRAY['אפליקציה עמוסה באפשרויות שלוקח זמן ללמוד'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש"}','published','חלופה מצוינת ל-S8 Ultra עם דגש על ניקוי פינות וקצוות.',ARRAY['בתים עם הרבה פינות ורהיטים'],ARRAY['משתמשים שרוצים ממשק פשוט'],ARRAY['flagship','combo'],ARRAY['robot-vacuums']),
('dreame-x40-ultra','Dreame X40 Ultra','Dreame',(select id from categories where slug='robot-vacuums'),9.3,'הדגל של Dreame עם רגליים מכניות שמרימות את כל הרובוט כדי לטפס על מפתני דלת ושטיחים עבים.',ARRAY['רגליים מכניות מטפסות על מכשולים גבוהים במיוחד','שאיבה בעוצמה גבוהה מאוד','תחנה עצמאית מלאה'],ARRAY['רעש גבוה יותר בזמן טיפוס','מחיר גבוה'],'{"ניווט":"LiDAR","טיפוס מכשולים":"עד כ-6 ס״מ עם מנגנון רגליים","תחנה":"ריקון, שטיפה וייבוש"}','published','המתאים ביותר לבתים עם מפתני דלתות גבוהים או שטיחים עבים שרובוטים אחרים נתקעים בהם.',ARRAY['בתים עם מפתנים ושטיחים עבים'],ARRAY['דירות עם רצפה שטוחה לגמרי, שם היתרון מיותר'],ARRAY['flagship','combo'],ARRAY['robot-vacuums']),
('dreame-l20-ultra','Dreame L20 Ultra','Dreame',(select id from categories where slug='robot-vacuums'),8.9,'דגם מאוזן של Dreame עם זרוע מגב מתרוממת ותחנה מלאה, ברמת מחיר נמוכה יותר מה-X40.',ARRAY['זרוע מגב מתרוממת מעל שטיחים','תחנה עצמאית מלאה','יחס מחיר-ביצועים טוב'],ARRAY['פחות עוצמתי מהדגם X40 בטיפוס מכשולים'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש"}','published','נקודת כניסה טובה למערכת מלאה של Dreame בלי לשלם על היכולות הכי אקסטרימיות.',ARRAY['משפחות שרוצות מערכת מלאה במחיר סביר'],ARRAY['בתים עם מכשולים גבוהים במיוחד'],ARRAY['combo'],ARRAY['robot-vacuums']),
('dreame-bot-l10s-ultra','Dreame Bot L10s Ultra','Dreame',(select id from categories where slug='robot-vacuums'),8.5,'אחד הדגמים הראשונים שהציגו ניקוי אוטומטי של המגב בחום בתחנה, עדיין רלוונטי ובמחיר נגיש.',ARRAY['ניקוי מגב בחום בתחנה','שאיבה טובה ברמת מחיר בינונית'],ARRAY['ללא זרוע מגב מתרוממת — עלול להרטיב שטיחים'],'{"ניווט":"LiDAR","תחנה":"ריקון ושטיפת מגב בחום"}','published','אופציה ותיקה ומוכחת למי שמוכן להרים שטיחים ידנית לפני ניקוי.',ARRAY['בתים בלי שטיחים או עם שטיחים שקל להזיז'],ARRAY['בתים עם הרבה שטיחים קבועים'],ARRAY['combo'],ARRAY['robot-vacuums']),
('ecovacs-deebot-x2-omni','Ecovacs Deebot X2 Omni','Ecovacs',(select id from categories where slug='robot-vacuums'),9.0,'רובוט עגול עם תחנת Omni מלאה ומברשת ראשית ייחודית בצורת עלה שנועדה לצמצם הסתבכות שיער.',ARRAY['מברשת ראשית שמצמצמת הסתבכות שיער חיות','תחנה מלאה כולל ריקון ושטיפה','עיצוב עגול קלאסי ויציב'],ARRAY['פחות יעיל בפינות חדות בהשוואה לרובוטים בצורת D'],'{"ניווט":"LiDAR","מברשת":"עיצוב ייחודי נגד הסתבכות","תחנה":"ריקון, שטיפה וייבוש"}','published','בחירה טובה לבתים עם חיות מחמד בזכות המברשת הייעודית.',ARRAY['בתים עם כלבים וחתולים'],ARRAY['חללים עם הרבה פינות צרות'],ARRAY['combo','pets'],ARRAY['robot-vacuums']),
('ecovacs-deebot-t20-omni','Ecovacs Deebot T20 Omni','Ecovacs',(select id from categories where slug='robot-vacuums'),8.8,'דגם בצורת D של Ecovacs עם זרוע מגב מתרוממת ושאיבה חזקה, מתחרה ישיר לדגמי Roborock.',ARRAY['צורת D מגיעה טוב יותר לפינות','זרוע מגב מתרוממת מעל שטיחים','שאיבה חזקה'],ARRAY['אפליקציה פחות אינטואיטיבית מהמתחרות'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש"}','published','חלופה טובה לדגמי הדגל של Roborock ו-Dreame, עם דגש על פינות.',ARRAY['בתים עם הרבה רהיטים ופינות'],ARRAY['משתמשים שרגישים לממשק אפליקציה'],ARRAY['combo'],ARRAY['robot-vacuums']),
('ecovacs-deebot-x1-omni','Ecovacs Deebot X1 Omni','Ecovacs',(select id from categories where slug='robot-vacuums'),8.3,'הדור הקודם של קו ה-Omni, עדיין נמכר ומספק מערכת מלאה במחיר נמוך יותר מהדגמים החדשים.',ARRAY['תחנה מלאה במחיר נגיש יחסית','שאיבה סבירה מאוד לרוב הבתים'],ARRAY['ללא זרוע מגב מתרוממת','ניווט איטי יותר מהדגמים החדשים'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש"}','published','נקודת כניסה סבירה למערכת אומני מלאה במחיר נמוך מהדגל הנוכחי.',ARRAY['תקציב מוגבל שעדיין רוצה תחנה מלאה'],ARRAY['בתים עם הרבה שטיחים'],ARRAY['combo'],ARRAY['robot-vacuums']),
('xiaomi-mijia-x10-plus','Xiaomi Mijia Robot Vacuum X10+','Xiaomi',(select id from categories where slug='robot-vacuums'),8.4,'דגם משולב של שיאומי עם תחנת ריקון ושטיפה, ידוע ביחס מחיר-ביצועים חזק בשוק הישראלי.',ARRAY['מחיר תחרותי מאוד ביחס למפרט','אפליקציית Xiaomi Home נוחה'],ARRAY['תמיכה ושירות בישראל מוגבלים יותר ממותגים גדולים'],'{"ניווט":"LiDAR","תחנה":"ריקון ושטיפה"}','published','אחד מיחסי המחיר-ביצועים הטובים בשוק, בתנאי שמוכנים לוותר על שירות מותג גדול.',ARRAY['קונים מודעי תקציב'],ARRAY['מי שמחפש שירות ואחריות מקומיים חזקים'],ARRAY['value'],ARRAY['robot-vacuums']),
('xiaomi-robot-vacuum-s10-plus','Xiaomi Robot Vacuum S10+','Xiaomi',(select id from categories where slug='robot-vacuums'),8.1,'דגם קומפקטי יותר של שיאומי עם תחנת ריקון בלבד (ללא שטיפה אוטומטית בתחנה).',ARRAY['גוף רובוט דק במיוחד, נכנס מתחת לרהיטים נמוכים','מחיר נגיש'],ARRAY['התחנה מרוקנת אבק בלבד, לא שוטפת את המגב'],'{"ניווט":"LiDAR","גובה":"נמוך במיוחד לכניסה מתחת לרהיטים"}','published','מתאים לבתים עם רהיטים נמוכים שרובוטים עבים לא מגיעים מתחתם.',ARRAY['בתים עם ספות וארונות נמוכים'],ARRAY['מי שרוצה תחנת שטיפה אוטומטית מלאה'],ARRAY['compact'],ARRAY['robot-vacuums']),
('irobot-roomba-combo-j9-plus','iRobot Roomba Combo j9+','iRobot',(select id from categories where slug='robot-vacuums'),8.7,'הדגל המשולב של iRobot, עם זיהוי חפצים מבוסס AI שמרים את המגב ליד שטיחים וחפצים על הרצפה.',ARRAY['זיהוי AI מדויק של חפצים על הרצפה (כבלים, גרביים)','מגב מתרומם אוטומטית מעל שטיחים','מותג ותיק עם תמיכה רחבה'],ARRAY['שאיבה חלשה יחסית למתחרות הסיניות','מחיר גבוה ביחס למפרט'],'{"ניווט":"מצלמה + מיפוי vSLAM","תחנה":"ריקון עצמי"}','published','הבחירה למי שסומך על iRobot ומעדיף זיהוי חפצים אמין על פני שאיבה מקסימלית.',ARRAY['בתים עם ילדים וצעצועים על הרצפה'],ARRAY['מי שמחפש את השאיבה החזקה ביותר בשוק'],ARRAY['flagship','combo'],ARRAY['robot-vacuums']),
('irobot-roomba-j7-plus','iRobot Roomba j7+','iRobot',(select id from categories where slug='robot-vacuums'),8.0,'שואב בלבד (ללא שטיפה) עם אותה מערכת זיהוי חפצים מבוססת AI כמו דגם ה-Combo.',ARRAY['זיהוי AI מדויק שמונע הסתבכות בכבלים','תחנת ריקון עצמית אמינה'],ARRAY['ללא יכולת שטיפה כלל'],'{"ניווט":"מצלמה + AI","תחנה":"ריקון עצמי"}','published','למי שרוצה רק שאיבה אמינה בלי לשלם על שטיפה שלא ישתמשו בה.',ARRAY['בתים עם שטיח בלבד, בלי ריצוף קשיח'],ARRAY['בתים עם ריצוף שדורש שטיפה קבועה'],ARRAY['vacuum-only'],ARRAY['robot-vacuums']),
('eufy-robovac-x9-pro','Eufy RoboVac X9 Pro','Eufy (Anker)',(select id from categories where slug='robot-vacuums'),8.2,'דגם עם זרוע מגב מתרוממת במחיר נמוך משמעותית מהמתחרות היפניות והסיניות המובילות.',ARRAY['זרוע מגב מתרוממת במחיר נגיש יחסית','מותג Anker עם תמיכה סבירה'],ARRAY['אפליקציה בסיסית פחות עשירה מהמתחרות המובילות'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת"}','published','זרוע מגב מתרוממת בלי לשלם מחיר דגל — פשרה טובה לרוב הבתים.',ARRAY['תקציב בינוני שרוצה טכנולוגיית מגב מתרומם'],ARRAY['מי שרוצה את מלוא היכולות המתקדמות'],ARRAY['value'],ARRAY['robot-vacuums']),
('eufy-clean-x10-pro-omni','Eufy Clean X10 Pro Omni','Eufy (Anker)',(select id from categories where slug='robot-vacuums'),8.3,'מערכת Omni מלאה של Eufy במחיר תחרותי לתחנות ריקון-שטיפה-ייבוש.',ARRAY['תחנה מלאה במחיר נמוך מהמתחרות המובילות','שאיבה סבירה לשימוש יומיומי'],ARRAY['ניווט לפעמים פחות חלק מהדגמים היקרים יותר'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש"}','published','דרך נגישה למערכת Omni מלאה למי שלא צריך את הביצועים הכי מתקדמים.',ARRAY['משפחות עם תקציב מוגבל שרוצות תחנה מלאה'],ARRAY['בתים עם דרישות ניווט מורכבות'],ARRAY['value','combo'],ARRAY['robot-vacuums']),
('narwal-freo','Narwal Freo','Narwal',(select id from categories where slug='robot-vacuums'),8.6,'רובוט עם שני מגבים מסתובבים שנסחטים ומתנקים בתחנה, מיועד לניקוי ריצוף אינטנסיבי.',ARRAY['שני מגבים מסתובבים לשטיפה יסודית','תחנה עם ניקוי וייבוש מגבים'],ARRAY['פחות מוכר בישראל, זמינות שירות מוגבלת'],'{"ניווט":"LiDAR","שטיפה":"שני מגבים מסתובבים"}','published','שטיפה יסודית מאוד לבתים עם ריצוף קשיח דומיננטי.',ARRAY['בתים עם ריצוף קרמיקה או פרקט בעיקר'],ARRAY['בתים עם הרבה שטיח'],ARRAY['flagship'],ARRAY['robot-vacuums']),
('yeedi-cube','Yeedi Cube','Yeedi',(select id from categories where slug='robot-vacuums'),7.8,'דגם משולב במחיר נגיש עם תחנת ריקון ושטיפה, מיועד לתקציב נמוך יותר.',ARRAY['מחיר נמוך משמעותית מהמתחרות','תחנה כוללת ריקון ושטיפה'],ARRAY['שאיבה וניווט ברמה בסיסית יותר'],'{"ניווט":"LiDAR","תחנה":"ריקון ושטיפה"}','published','אופציה תקציבית לבית קטן שרק מתחיל עם רובוט ניקוי.',ARRAY['תקציב נמוך, דירה קטנה'],ARRAY['בתים גדולים או מורכבים'],ARRAY['budget'],ARRAY['robot-vacuums']),
('midea-m9','Midea M9','Midea',(select id from categories where slug='robot-vacuums'),7.9,'דגם משולב של Midea עם זרוע מגב מתרוממת במחיר תחרותי.',ARRAY['זרוע מגב מתרוממת במחיר נמוך יחסית','תחנה מלאה'],ARRAY['מותג פחות מוכר לצרכן הישראלי'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת"}','published','טכנולוגיית מגב מתרומם במחיר נגיש למי שלא מחפש מותג מוביל.',ARRAY['קונים מודעי תקציב שרוצים זרוע מגב'],ARRAY['מי שמחפש מותג עם היסטוריה ארוכה בישראל'],ARRAY['value'],ARRAY['robot-vacuums']),
('samsung-jet-bot-combo','Samsung Jet Bot Combo','Samsung',(select id from categories where slug='robot-vacuums'),8.0,'רובוט משולב של סמסונג עם תחנת ריקון ושטיפה, משתלב בקלות עם מכשירי SmartThings אחרים.',ARRAY['אינטגרציה טובה עם אקוסיסטם Samsung SmartThings','תמיכה ואחריות רחבה של סמסונג בישראל'],ARRAY['שאיבה סבירה אך לא מהחזקות בקטגוריה'],'{"ניווט":"LiDAR","תחנה":"ריקון ושטיפה"}','published','בחירה טבעית למי שכבר בתוך אקוסיסטם המכשירים החכמים של סמסונג.',ARRAY['בתים עם מכשירי Samsung חכמים נוספים'],ARRAY['מי שמחפש את השאיבה החזקה ביותר בשוק'],ARRAY['smart-home'],ARRAY['robot-vacuums']),
('lg-codezero-r9','LG CordZero R9','LG',(select id from categories where slug='robot-vacuums'),7.7,'דגם משולב של LG עם ניווט מבוסס מצלמה ותחנת ריקון ושטיפה.',ARRAY['אחריות ותמיכה של LG בישראל','עיצוב וגימור פרימיום'],ARRAY['פחות נפוץ בהשוואות ובביקורות בינלאומיות'],'{"ניווט":"מצלמה","תחנה":"ריקון ושטיפה"}','published','אופציה עם גיבוי מותג חזק בישראל למי שפחות משווה מפרטים לעומק.',ARRAY['קונים שמעדיפים מותג מוכר עם שירות מקומי'],ARRAY['מי שרוצה את המפרט הטכני המתקדם ביותר'],ARRAY['brand'],ARRAY['robot-vacuums'])
on conflict (slug) do nothing;
