-- Continuation of 20260730050000_seed_real_products.sql — see that file's
-- header for the price/image/score rationale, which applies here too.

-- ===================== mops (17) =====================
-- Standalone or mopping-forward models, distinct from the vacuum-led
-- combo units already listed under robot-vacuums.
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('irobot-braava-jet-m6','iRobot Braava jet m6','iRobot',(select id from categories where slug='mops'),8.3,'רובוט שטיפה עצמאי (לא שואב) שמשתמש בסילון מים ממוקד לכתמים קשים, עובד יחד עם רובוטי Roomba תואמים.',ARRAY['סילון מים ממוקד לכתמים יבשים','משקל קל ומעבר קל מתחת לרהיטים'],ARRAY['לא שואב — נדרש ניקוי אבק לפני שימוש'],'{"סוג":"שטיפה בלבד","שיטה":"סילון מים + מגב רוטט"}','published','הכי טוב כמכשיר משלים אחרי שואב, לא כתחליף לו.',ARRAY['בתים שכבר יש בהם שואב רובוטי נפרד'],ARRAY['מי שרוצה מכשיר אחד שגם שואב וגם שוטף'],ARRAY['mop-only'],ARRAY['mops']),
('irobot-braava-380t','iRobot Braava 380t','iRobot',(select id from categories where slug='mops'),7.4,'דגם ותיק וקומפקטי של Braava, מנגב יבש או רטוב בעדינות, מתאים לפרקט רגיש.',ARRAY['עדין מאוד על פרקט ורצפות עץ','מחיר נגיש'],ARRAY['ללא מיפוי חכם — עובד בתבנית פשוטה יותר'],'{"סוג":"שטיפה בלבד","ניווט":"בסיסי, ללא LiDAR"}','published','אופציה זולה ועדינה לרצפות עץ שרגישות למכשירים כבדים יותר.',ARRAY['בתים עם פרקט רגיש'],ARRAY['דירות גדולות שדורשות ניווט חכם'],ARRAY['budget','mop-only'],ARRAY['mops']),
('xiaomi-mi-robot-mop-2-pro','Xiaomi Mi Robot Mop 2 Pro','Xiaomi',(select id from categories where slug='mops'),7.9,'רובוט שטיפה של שיאומי עם מכל מים לחוץ ובקרת זרימה, במחיר תחרותי.',ARRAY['בקרת זרימת מים מדויקת','מחיר נגיש ביחס ליכולות'],ARRAY['תמיכה מקומית מוגבלת יותר'],'{"סוג":"שטיפה בלבד","מיכל מים":"לחוץ עם בקרת זרימה"}','published','שטיפה ממוקדת במחיר טוב, בלי לשלם על יכולות שאיבה שלא צריך.',ARRAY['בתים שכבר יש בהם שואב נפרד'],ARRAY['מי שרוצה מכשיר אחד שעושה הכל'],ARRAY['value','mop-only'],ARRAY['mops']),
('roborock-qrevo-curv','Roborock Qrevo Curv','Roborock',(select id from categories where slug='mops'),9.0,'הדגם המתקדם ביותר של Roborock לשטיפה, עם זרוע מגב שמתרוממת ומברשת ראשית שמתרוממת גם היא מעל שטיחים.',ARRAY['גם מברשת האבק וגם המגב מתרוממים בנפרד מעל שטיחים','תחנה עם שטיפה בחום וייבוש'],ARRAY['מחיר מהגבוהים בקטגוריה'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת + מברשת מתרוממת"}','published','הפתרון הכי מתקדם למי שרוצה שילוב שאיבה ושטיפה בלי פשרות על שטיחים.',ARRAY['בתים עם שטיחים רבים וריצוף מעורב'],ARRAY['תקציב מוגבל'],ARRAY['flagship','combo'],ARRAY['mops']),
('roborock-qrevo-s','Roborock Qrevo S','Roborock',(select id from categories where slug='mops'),8.6,'גרסה נגישה יותר בקו ה-Qrevo, עם זרוע מגב מתרוממת ותחנה מלאה.',ARRAY['זרוע מגב מתרוממת','תחנה עצמאית מלאה'],ARRAY['פחות עוצמתי מדגם ה-Curv המתקדם'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת"}','published','רוב היתרונות של קו ה-Qrevo במחיר נגיש יותר.',ARRAY['משפחות עם תקציב בינוני'],ARRAY['מי שצריך את היכולות המתקדמות ביותר'],ARRAY['combo'],ARRAY['mops']),
('dreame-mova-p10-pro','Dreame Mova P10 Pro','Dreame (Mova)',(select id from categories where slug='mops'),8.1,'מותג המשנה Mova של Dreame, ממוקד שטיפה עם תחנת ניקוי מגב עצמאית.',ARRAY['תחנת ניקוי מגב יעילה','שטיפה יסודית לריצוף קשיח'],ARRAY['מותג משנה פחות מוכר'],'{"סוג":"שטיפה עם דגש","תחנה":"ניקוי מגב עצמאי"}','published','שטיפה איכותית במחיר נמוך מדגמי הדגל הראשיים של Dreame.',ARRAY['בתים עם ריצוף קשיח דומיננטי'],ARRAY['בתים עם שטיח נרחב'],ARRAY['value'],ARRAY['mops']),
('cecotec-conga-4090','Cecotec Conga 4090','Cecotec',(select id from categories where slug='mops'),7.3,'דגם ספרדי משולב במחיר נמוך, פופולרי באירופה ומתחיל להופיע בשוק הישראלי.',ARRAY['מחיר נמוך משמעותית מהמותגים המובילים','תחנת ריקון ושטיפה בסיסית'],ARRAY['זמינות חלקי חילוף ותמיכה בישראל מוגבלת'],'{"ניווט":"LiDAR","תחנה":"ריקון ושטיפה"}','published','אופציה תקציבית מאוד למי שמוכן לוותר על תמיכה מקומית חזקה.',ARRAY['תקציב נמוך מאוד'],ARRAY['מי שרוצה שירות ואחריות מקומיים חזקים'],ARRAY['budget'],ARRAY['mops']),
('narwal-t10','Narwal T10','Narwal',(select id from categories where slug='mops'),8.4,'רובוט שטיפה-שאיבה עם שני מגבים מסתובבים, מהדגמים הראשונים שהציגו את הטכנולוגיה הזו.',ARRAY['שני מגבים מסתובבים לשטיפה עמוקה','תחנה עם ניקוי מגבים'],ARRAY['גדול ותופס מקום'],'{"שטיפה":"שני מגבים מסתובבים","תחנה":"ניקוי וייבוש מגבים"}','published','שטיפה עמוקה ויסודית לבתים עם ריצוף קשיח נרחב.',ARRAY['בתים עם ריצוף קרמיקה או שיש'],ARRAY['דירות קטנות עם מקום אחסון מוגבל'],ARRAY['deep-clean'],ARRAY['mops']),
('narwal-freo-x-ultra','Narwal Freo X Ultra','Narwal',(select id from categories where slug='mops'),8.9,'הדגל המשולב של Narwal עם זרוע מגב מתרוממת ותחנה מלאה כולל חיטוי בקיטור.',ARRAY['אפשרות חיטוי בקיטור בתחנה','זרוע מגב מתרוממת','שני מגבים מסתובבים'],ARRAY['מהיקרים בקטגוריה'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה, ייבוש וחיטוי קיטור"}','published','המערכת המקיפה ביותר לשטיפה, כולל חיטוי, למי שמוכן לשלם על זה.',ARRAY['בתים עם ילדים קטנים או חיות מחמד'],ARRAY['תקציב מוגבל'],ARRAY['flagship'],ARRAY['mops']),
('yeedi-mop-station-pro','Yeedi Mop Station Pro','Yeedi',(select id from categories where slug='mops'),7.6,'רובוט משולב תקציבי עם תחנת שטיפה עצמאית.',ARRAY['מחיר נגיש','תחנת שטיפה עצמאית'],ARRAY['ביצועי ניווט בסיסיים יותר'],'{"ניווט":"LiDAR","תחנה":"שטיפה עצמאית"}','published','נקודת כניסה תקציבית למערכת עם תחנת שטיפה עצמאית.',ARRAY['תקציב מוגבל'],ARRAY['בתים גדולים ומורכבים'],ARRAY['budget'],ARRAY['mops']),
('ecovacs-deebot-n30-omni','Ecovacs Deebot N30 Omni','Ecovacs',(select id from categories where slug='mops'),8.0,'דגם Omni נגיש יותר של Ecovacs עם זרוע מגב מתרוממת.',ARRAY['זרוע מגב מתרוממת במחיר סביר','תחנה מלאה'],ARRAY['שאיבה בינונית ביחס לדגלים'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב מתרוממת"}','published','איזון טוב בין מחיר ליכולות שטיפה מתקדמות.',ARRAY['משפחות עם תקציב בינוני'],ARRAY['מי שצריך שאיבה מקסימלית'],ARRAY['value','combo'],ARRAY['mops']),
('ecovacs-deebot-t30s-combo','Ecovacs Deebot T30S Combo','Ecovacs',(select id from categories where slug='mops'),8.5,'דגם עם זרוע רובוטית שמזיזה לצד את המגב כשמזהה שטיח, בנוסף להרמה.',ARRAY['זרוע רובוטית שמזיזה את המגב הצידה משטיחים','תחנה מלאה עם ריקון ושטיפה'],ARRAY['מנגנון מורכב יותר לתחזוקה'],'{"ניווט":"LiDAR","שטיפה":"זרוע מגב נעה + מתרוממת"}','published','פתרון חכם במיוחד לבתים עם שטיחים בצורות לא סדירות.',ARRAY['בתים עם שטיחים רבים בצורות שונות'],ARRAY['בתים בלי שטיחים כלל'],ARRAY['combo'],ARRAY['mops']),
('tineco-floor-one-s7','Tineco Floor One S7','Tineco',(select id from categories where slug='mops'),7.5,'לא רובוט אוטונומי אלא שוטף רצפה אלחוטי מונע-יד עם חיישן לכלוך — נכלל כאן כאופציה למי שמחפש שטיפה יעילה בלי רובוט מלא.',ARRAY['ניקוי ושטיפה בו-זמנית בתנועה אחת','חיישן שמזהה לכלוך ומתאים עוצמה'],ARRAY['דורש הפעלה ידנית, לא אוטונומי'],'{"סוג":"מונע-יד, לא אוטונומי","ניקוי":"רטוב ויבש בו-זמנית"}','published','למי שרוצה שטיפה יסודית בשליטה ידנית בלי להשקיע ברובוט מלא.',ARRAY['מי שמעדיף שליטה ידנית מלאה'],ARRAY['מי שמחפש פתרון אוטונומי לחלוטין'],ARRAY['manual'],ARRAY['mops']),
('tineco-floor-one-switch','Tineco Floor One Switch','Tineco',(select id from categories where slug='mops'),7.2,'דגם קל משקל ומתקפל של Tineco, מונע-יד, נוח לאחסון בדירות קטנות.',ARRAY['קל וקומפקטי לאחסון','מנקה רטוב ויבש בו-זמנית'],ARRAY['לא אוטונומי — דורש הפעלה ידנית'],'{"סוג":"מונע-יד","משקל":"קל יחסית"}','published','אופציה קלה לאחסון לדירות קטנות שמעדיפות שליטה ידנית.',ARRAY['דירות קטנות עם מקום אחסון מוגבל'],ARRAY['מי שרוצה רובוט אוטונומי'],ARRAY['manual','compact'],ARRAY['mops']),
('switchbot-k10-plus-pro-combo','SwitchBot K10+ Pro Combo','SwitchBot',(select id from categories where slug='mops'),7.8,'רובוט משולב זעיר וקומפקטי במיוחד, מיועד לדירות קטנות עם מסדרונות צרים.',ARRAY['מהרובוטים הקטנים ביותר בשוק','נכנס לפינות ומעברים צרים'],ARRAY['מכל אבק ומים קטנים, דורש ריקון תכוף יותר'],'{"גודל":"קומפקטי במיוחד","תחנה":"ריקון ושטיפה"}','published','הכי טוב לדירות קטנות עם מסדרונות צרים שרובוטים רגילים לא עוברים בהם.',ARRAY['דירות קטנות ומעברים צרים'],ARRAY['בתים גדולים שדורשים מכל גדול'],ARRAY['compact'],ARRAY['mops']),
('anker-eufy-omni-c20','Anker Eufy Omni C20','Eufy (Anker)',(select id from categories where slug='mops'),7.7,'דגם Omni נגיש של Eufy עם תחנה מלאה, ממוקד שוק תקציבי-בינוני.',ARRAY['תחנה מלאה במחיר תחרותי','מותג עם תמיכה בישראל'],ARRAY['שאיבה וניווט ברמה בינונית'],'{"ניווט":"LiDAR","תחנה":"ריקון, שטיפה וייבוש"}','published','מערכת מלאה במחיר נגיש למי שלא צריך ביצועי דגל.',ARRAY['תקציב בינוני'],ARRAY['בתים גדולים ומורכבים במיוחד'],ARRAY['value','combo'],ARRAY['mops']),
('ilife-w400','ILIFE W400','ILIFE',(select id from categories where slug='mops'),7.0,'רובוט שטיפה בלבד, קומפקטי ותקציבי, מיועד לדירות קטנות עם ריצוף קשיח.',ARRAY['מחיר נמוך מאוד','קל לתפעול'],ARRAY['ללא מיפוי חכם מתקדם'],'{"סוג":"שטיפה בלבד","ניווט":"בסיסי"}','published','שטיפה בסיסית ותקציבית לדירה קטנה עם ריצוף קשיח.',ARRAY['תקציב נמוך מאוד'],ARRAY['בתים גדולים או עם שטיחים'],ARRAY['budget','mop-only'],ARRAY['mops'])
on conflict (slug) do nothing;

-- ===================== lawn-mowers (15) =====================
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('husqvarna-automower-450x','Husqvarna Automower 450X','Husqvarna',(select id from categories where slug='lawn-mowers'),9.1,'אחד ממכסחות הדשא הרובוטיות הוותיקות והמוכרות בעולם, עם ניווט GPS מדויק וחיתוך אקראי טבעי.',ARRAY['ניווט GPS מדויק עם מפת גבולות וירטואלית','חיתוך אקראי שמונע פסים ומשאיר דשא בריא','אפליקציה מפותחת עם התראות'],ARRAY['מחיר גבוה כולל התקנה מקצועית מומלצת'],'{"ניווט":"GPS + כבל היקפי אופציונלי","שטח מומלץ":"עד כ-5,000 מ״ר"}','published','המותג הבטוח והמוכח ביותר בקטגוריה, לחצרות גדולות ומורכבות.',ARRAY['חצרות גדולות עם צורות מורכבות'],ARRAY['חצרות קטנות שלא מצדיקות את המחיר'],ARRAY['premium','gps'],ARRAY['lawn-mowers']),
('husqvarna-automower-315x','Husqvarna Automower 315X','Husqvarna',(select id from categories where slug='lawn-mowers'),8.6,'דגם קטן וקומפקטי יותר בקו Automower, מתאים לחצרות ביתיות רגילות.',ARRAY['ניווט GPS מדויק','גודל קומפקטי מתאים לחצר ביתית'],ARRAY['שטח מכוסה קטן יותר מהדגמים הגדולים בקו'],'{"ניווט":"GPS","שטח מומלץ":"עד כ-1,600 מ״ר"}','published','נקודת כניסה טובה לאמינות Husqvarna בחצר ביתית רגילה.',ARRAY['חצרות ביתיות בגודל בינוני'],ARRAY['שטחים גדולים במיוחד'],ARRAY['gps'],ARRAY['lawn-mowers']),
('worx-landroid-vision','Worx Landroid Vision','Worx',(select id from categories where slug='lawn-mowers'),8.3,'דגם מתקדם של Worx שמשתמש במצלמות במקום כבל היקפי מסורתי לזיהוי גבולות החצר.',ARRAY['אפשרות התקנה ללא כבל היקפי (ניווט חזותי)','אפליקציה נוחה עם מיפוי אוטומטי'],ARRAY['ביצועי הזיהוי החזותי תלויים בתאורה ובעונה'],'{"ניווט":"מצלמות (ללא כבל היקפי)","שטח מומלץ":"עד כ-800 מ״ר"}','published','פתרון מודרני שחוסך התקנת כבל היקפי, למי שמוכן לסמוך על טכנולוגיית ראייה.',ARRAY['חצרות עם גבולות פשוטים יחסית'],ARRAY['חצרות מורכבות מאוד עם הרבה מכשולים'],ARRAY['camera-based'],ARRAY['lawn-mowers']),
('worx-landroid-m500','Worx Landroid M500','Worx',(select id from categories where slug='lawn-mowers'),8.0,'הדגם הקלאסי של Worx עם כבל היקפי מסורתי, מוכר ונפוץ בישראל.',ARRAY['מחיר תחרותי ביחס למותגים הפרימיום','זמינות שירות וחלפים טובה בישראל'],ARRAY['דורש כבל היקפי בהתקנה ראשונית'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-500 מ״ר"}','published','אחת האופציות הנפוצות והמתוחזקות ביותר בישראל למחיר סביר.',ARRAY['חצרות ביתיות בגודל בינוני'],ARRAY['מי שרוצה להימנע מהתקנת כבל'],ARRAY['value'],ARRAY['lawn-mowers']),
('robomow-rs630','Robomow RS630','Robomow (Friendly Robotics)',(select id from categories where slug='lawn-mowers'),8.4,'מכסחת רובוטית של Friendly Robotics, חברה ישראלית — עם תמיכה ושירות מקומיים מהמובילים בקטגוריה.',ARRAY['חברה ופיתוח ישראליים עם שירות מקומי חזק','חיתוך ברוחב גדול שמקצר זמני כיסוי'],ARRAY['גוף גדול ופחות קל לתמרון בפינות צרות'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-3,000 מ״ר"}','published','בחירה מצוינת בזכות תמיכה ישראלית מקומית ורוחב חיתוך גדול.',ARRAY['חצרות גדולות בישראל שרוצות שירות מקומי'],ARRAY['חצרות עם הרבה פינות צרות'],ARRAY['israeli','local-support'],ARRAY['lawn-mowers']),
('robomow-rk1000','Robomow RK1000','Robomow (Friendly Robotics)',(select id from categories where slug='lawn-mowers'),8.1,'דגם ביתי קומפקטי יותר של Robomow, מתאים לחצרות ביתיות רגילות בישראל.',ARRAY['שירות ותמיכה ישראליים','קל יחסית להתקנה'],ARRAY['שטח כיסוי מוגבל יותר מהדגמים הגדולים'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-1,000 מ״ר"}','published','אופציה ישראלית אמינה לחצר ביתית רגילה.',ARRAY['חצרות ביתיות קטנות-בינוניות'],ARRAY['שטחים מסחריים גדולים'],ARRAY['israeli','local-support'],ARRAY['lawn-mowers']),
('gardena-smart-sileno','Gardena Smart Sileno','Gardena',(select id from categories where slug='lawn-mowers'),8.2,'קו מכסחות של גרמניה, ידוע בשקט תפעולי ואינטגרציה עם אקוסיסטם Gardena Smart.',ARRAY['תפעול שקט במיוחד','אינטגרציה עם מערכות השקיה חכמות של Gardena'],ARRAY['מחיר גבוה יחסית לשטח שמכסה'],'{"ניווט":"כבל היקפי","רעש":"נמוך במיוחד"}','published','הכי שקטה בקטגוריה, טובה לחצרות צמודות לשכנים.',ARRAY['חצרות בשכונות צפופות'],ARRAY['תקציב מוגבל'],ARRAY['quiet','premium'],ARRAY['lawn-mowers']),
('segway-navimow-i105','Segway Navimow i105','Segway',(select id from categories where slug='lawn-mowers'),8.5,'מכסחת ללא כבל היקפי בכלל, מבוססת GPS-RTK מדויק במיוחד.',ARRAY['התקנה ללא כבל היקפי כלל','דיוק GPS-RTK גבוה מאוד'],ARRAY['תלוי בקליטת אות GPS טובה בחצר'],'{"ניווט":"GPS-RTK, ללא כבל היקפי","שטח מומלץ":"עד כ-1,000 מ״ר"}','published','הפתרון הכי נוח להתקנה בזכות ביטול הכבל ההיקפי, בכפוף לקליטת GPS טובה.',ARRAY['חצרות פתוחות עם קליטת GPS טובה'],ARRAY['חצרות מוקפות מבנים גבוהים שחוסמים אות'],ARRAY['gps','no-wire'],ARRAY['lawn-mowers']),
('segway-navimow-x330','Segway Navimow X330','Segway',(select id from categories where slug='lawn-mowers'),8.7,'דגם מתקדם בקו Navimow עם שטח כיסוי גדול יותר וניווט RTK מדויק.',ARRAY['שטח כיסוי גדול','ללא כבל היקפי'],ARRAY['מחיר גבוה יחסית'],'{"ניווט":"GPS-RTK","שטח מומלץ":"עד כ-3,000 מ״ר"}','published','אופציה מתקדמת לחצרות גדולות שרוצות להימנע מכבל היקפי.',ARRAY['חצרות גדולות עם קליטת GPS טובה'],ARRAY['תקציב מוגבל'],ARRAY['gps','no-wire'],ARRAY['lawn-mowers']),
('ecovacs-goat-a3000','Ecovacs Goat A3000','Ecovacs',(select id from categories where slug='lawn-mowers'),8.3,'כניסתה של Ecovacs לקטגוריית מכסחות הדשא, עם ניווט LiDAR במקום GPS בלבד.',ARRAY['ניווט LiDAR מוסיף דיוק במכשולים','אפליקציה דומה למוצרי השאיבה המוכרים של Ecovacs'],ARRAY['מותג חדש יחסית בקטגוריית מכסחות'],'{"ניווט":"LiDAR + GPS","שטח מומלץ":"עד כ-800 מ״ר"}','published','שילוב מעניין של טכנולוגיית LiDAR ממוצרי שאיבה בעולם מכסחות הדשא.',ARRAY['חצרות עם מכשולים רבים'],ARRAY['מי שמעדיף מותג ותיק בקטגוריה'],ARRAY['lidar'],ARRAY['lawn-mowers']),
('mammotion-luba-2','Mammotion Luba 2 AWD','Mammotion',(select id from categories where slug='lawn-mowers'),8.4,'מכסחת עם הנעה בארבעה גלגלים (AWD) שמתמודדת טוב עם שיפועים תלולים, ללא כבל היקפי.',ARRAY['הנעת AWD מתמודדת עם שיפועים תלולים','ללא כבל היקפי — ניווט RTK'],ARRAY['משקל כבד יחסית'],'{"ניווט":"GPS-RTK","הנעה":"ארבעה גלגלים (AWD)"}','published','הבחירה הטובה ביותר לחצרות עם שיפועים ומדרונות.',ARRAY['חצרות עם שיפועים ומדרונות'],ARRAY['חצרות שטוחות פשוטות'],ARRAY['awd','no-wire'],ARRAY['lawn-mowers']),
('yarbo-lawn-mowing-module','Yarbo Lawn Mowing Module','Yarbo',(select id from categories where slug='lawn-mowers'),7.9,'מודול כיסוח בתוך מערכת רובוטית מודולרית רחבה יותר של Yarbo (כולל מודולים לפינוי שלג ועלים).',ARRAY['חלק ממערכת מודולרית להחלפת ראשים לפי עונה','פוטנציאל שימוש כל השנה'],ARRAY['מוצר חדש יחסית, פחות מוכח בטווח ארוך'],'{"ניווט":"GPS-RTK","מערכת":"מודולרית (כיסוח, שלג, עלים)"}','published','מעניין למי שרוצה פלטפורמה אחת לכל עבודות החצר, לא רק כיסוח.',ARRAY['בעלי חצר שרוצים פתרון שנתי מלא'],ARRAY['מי שרוצה רק מכסחת פשוטה'],ARRAY['modular'],ARRAY['lawn-mowers']),
('husqvarna-automower-310-mark-ii','Husqvarna Automower 310 Mark II','Husqvarna',(select id from categories where slug='lawn-mowers'),8.3,'דגם כניסה בקו Automower עם אמינות המותג במחיר נגיש יותר.',ARRAY['אמינות מותג Husqvarna','מחיר נגיש יחסית לקו המוצרים'],ARRAY['ללא GPS מלא כמו הדגמים המתקדמים'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-1,000 מ״ר"}','published','נקודת כניסה משתלמת לאיכות Husqvarna.',ARRAY['חצרות ביתיות בגודל בינוני'],ARRAY['חצרות גדולות ומורכבות'],ARRAY['value'],ARRAY['lawn-mowers']),
('worx-landroid-l1500','Worx Landroid L1500','Worx',(select id from categories where slug='lawn-mowers'),8.1,'דגם גדול בקו Worx לחצרות רחבות במיוחד.',ARRAY['שטח כיסוי גדול','מחיר תחרותי ביחס לשטח'],ARRAY['דורש כבל היקפי ארוך יותר להתקנה'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-1,500 מ״ר"}','published','אופציה משתלמת לחצרות גדולות שלא רוצות לשלם מחיר פרימיום.',ARRAY['חצרות גדולות'],ARRAY['חצרות קטנות'],ARRAY['value'],ARRAY['lawn-mowers']),
('gardena-sileno-city','Gardena Sileno City','Gardena',(select id from categories where slug='lawn-mowers'),7.8,'דגם עירוני קומפקטי של Gardena, מיועד לחצרות קטנות בעיר.',ARRAY['גודל קומפקטי מתאים לחצרות עירוניות קטנות','שקט תפעולי'],ARRAY['שטח כיסוי מוגבל'],'{"ניווט":"כבל היקפי","שטח מומלץ":"עד כ-300 מ״ר"}','published','מכסחת קומפקטית ושקטה לחצר עירונית קטנה.',ARRAY['חצרות עירוניות קטנות'],ARRAY['חצרות כפריות גדולות'],ARRAY['compact','quiet'],ARRAY['lawn-mowers'])
on conflict (slug) do nothing;
