-- Continuation — see 20260730050000_seed_real_products.sql header.

-- ===================== pool-cleaners (13) =====================
-- Maytronics (Dolphin) is an Israeli company (Kibbutz Yizre'el) and one
-- of the global category leaders — genuinely, not as local flavor.
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('maytronics-dolphin-m400','Dolphin M400','Maytronics',(select id from categories where slug='pool-cleaners'),9.0,'דגם דגל של מייטרוניקס (חברה ישראלית), מנקה קרקעית, דפנות וקו המים עם סינון ברמה גבוהה.',ARRAY['חברה ופיתוח ישראליים, שירות מקומי מהמובילים','מנקה קרקעית, דפנות וקו מים בפעולה אחת','מסנני PowerStream מתחלפים לפי סוג לכלוך'],ARRAY['מחיר גבוה יחסית'],'{"ניקוי":"קרקעית, דפנות וקו מים","סינון":"מסנני PowerStream מתחלפים"}','published','הבחירה הבטוחה למי שרוצה מותג ישראלי מוביל עם שירות מקומי מלא.',ARRAY['בריכות ביתיות בכל הגדלים'],ARRAY['תקציב מוגבל מאוד'],ARRAY['israeli','flagship'],ARRAY['pool-cleaners']),
('maytronics-dolphin-e10','Dolphin E10','Maytronics',(select id from categories where slug='pool-cleaners'),8.2,'דגם כניסה נגיש של מייטרוניקס, קל ופשוט לתפעול לבריכות ביתיות קטנות-בינוניות.',ARRAY['מחיר נגיש יחסית לקו המוצרים','קל ופשוט לתפעול'],ARRAY['ללא ניקוי דפנות מלא כמו הדגמים המתקדמים'],'{"ניקוי":"קרקעית בעיקר","משקל":"קל יחסית"}','published','נקודת כניסה משתלמת למותג ישראלי מוביל.',ARRAY['בריכות קטנות-בינוניות'],ARRAY['בריכות גדולות שדורשות ניקוי דפנות מלא'],ARRAY['israeli','value'],ARRAY['pool-cleaners']),
('maytronics-dolphin-s300','Dolphin S300','Maytronics',(select id from categories where slug='pool-cleaners'),8.8,'דגם עם שלט רחוק לניווט ידני, בנוסף לניקוי אוטומטי מלא.',ARRAY['שלט רחוק לניקוי נקודתי ידני','ניקוי קרקעית ודפנות מלא'],ARRAY['מחיר בקצה הגבוה'],'{"ניקוי":"קרקעית ודפנות","שליטה":"אוטומטי + שלט רחוק ידני"}','published','גמישות נדירה בין ניקוי אוטומטי מלא לשליטה ידנית נקודתית.',ARRAY['בעלי בריכות שרוצים שליטה ידנית לפעמים'],ARRAY['מי שמחפש רק אוטומציה מלאה'],ARRAY['israeli'],ARRAY['pool-cleaners']),
('aiper-seagull-pro','Aiper Seagull Pro','Aiper',(select id from categories where slug='pool-cleaners'),8.3,'רובוט בריכה אלחוטי לגמרי (ללא כבל), נטען בסוללה, מגמישות שימוש גבוהה.',ARRAY['ללא כבל כלל — ניידות מלאה','טעינה בסוללה נוחה לאחסון'],ARRAY['זמן ריצה מוגבל לפי קיבולת הסוללה'],'{"חשמל":"סוללה נטענת, ללא כבל","ניווט":"מיפוי חכם"}','published','הכי נוח לתפעול בזכות היעדר כבל, לבריכות שרוצות פתרון גמיש.',ARRAY['בריכות בלי גישה נוחה לשקע חשמל'],ARRAY['בריכות גדולות שדורשות ריצה ארוכה ברצף'],ARRAY['cordless'],ARRAY['pool-cleaners']),
('aiper-scuba-x1','Aiper Scuba X1','Aiper',(select id from categories where slug='pool-cleaners'),8.5,'דגם אלחוטי מתקדם עם ניווט חכם ומיפוי בריכה, מתמודד גם עם דפנות.',ARRAY['ניקוי קרקעית ודפנות אלחוטי','מיפוי חכם של הבריכה'],ARRAY['מחיר גבוה יחסית לקטגוריית האלחוטיים'],'{"חשמל":"סוללה נטענת","ניקוי":"קרקעית ודפנות"}','published','שילוב טוב בין נוחות אלחוטית ליכולות ניקוי מקיפות.',ARRAY['בריכות בינוניות-גדולות בלי גישה נוחה לחשמל'],ARRAY['תקציב מוגבל'],ARRAY['cordless'],ARRAY['pool-cleaners']),
('beatbot-aquasense-2','Beatbot AquaSense 2','Beatbot',(select id from categories where slug='pool-cleaners'),8.6,'רובוט 3-ב-1 שמנקה גם את פני המים (קליטת עלים צפים), גם קרקעית וגם דפנות.',ARRAY['ניקוי משטח המים בנוסף לקרקעית ודפנות','אלחוטי לגמרי'],ARRAY['מחיר גבוה'],'{"ניקוי":"פני מים, קרקעית ודפנות","חשמל":"סוללה נטענת"}','published','הפתרון המקיף ביותר שמכסה גם את פני המים, לא רק קרקעית ודפנות.',ARRAY['בריכות עם הרבה עלים ולכלוך צף'],ARRAY['תקציב מוגבל'],ARRAY['premium','cordless'],ARRAY['pool-cleaners']),
('polaris-9550-sport','Polaris 9550 Sport','Polaris',(select id from categories where slug='pool-cleaners'),8.4,'מותג ותיק בעולם ניקוי הבריכות, עם מערכת ניווט 4WD לכיסוי יסודי.',ARRAY['הנעת 4WD מטפסת טוב על דפנות','מותג ותיק עם מוניטין ארוך'],ARRAY['דורש כבל חשמלי לחיבור'],'{"הנעה":"4WD","ניקוי":"קרקעית ודפנות"}','published','מותג מוכח לאורך שנים, טוב לבריכות עם דפנות משופעות.',ARRAY['בריכות עם דפנות משופעות'],ARRAY['מי שרוצה פתרון אלחוטי לגמרי'],ARRAY['established'],ARRAY['pool-cleaners']),
('polaris-alpha-iq-plus','Polaris Alpha iQ+','Polaris',(select id from categories where slug='pool-cleaners'),8.9,'הדגל של Polaris עם ניווט חכם מבוסס מפה וזיכרון של צורת הבריכה.',ARRAY['ניווט חכם עם זיכרון צורת הבריכה','ניקוי יסודי כולל קו המים'],ARRAY['מחיר גבוה'],'{"ניווט":"מיפוי חכם עם זיכרון","ניקוי":"קרקעית, דפנות וקו מים"}','published','אחד הדגמים המתקדמים ביותר בשוק לבריכות גדולות ומורכבות.',ARRAY['בריכות גדולות בצורות לא סטנדרטיות'],ARRAY['תקציב מוגבל'],ARRAY['flagship'],ARRAY['pool-cleaners']),
('hayward-tigershark','Hayward TigerShark','Hayward',(select id from categories where slug='pool-cleaners'),7.9,'רובוט בריכה אמין ופשוט לתפעול ממותג ותיק בתחום ציוד הבריכות.',ARRAY['פשוט לתפעול ותחזוקה','מותג ותיק עם זמינות חלקים'],ARRAY['פחות תכונות חכמות מהמתחרות החדשות'],'{"ניקוי":"קרקעית ודפנות","תפעול":"פשוט, כפתור אחד"}','published','פתרון פשוט ואמין למי שלא צריך תכונות חכמות מתקדמות.',ARRAY['בעלי בריכה שרוצים פשטות'],ARRAY['מי שרוצה מיפוי חכם ואפליקציה מתקדמת'],ARRAY['reliable'],ARRAY['pool-cleaners']),
('dolphin-active-60','Dolphin Active 60','Maytronics',(select id from categories where slug='pool-cleaners'),8.0,'דגם ביניים בקו Dolphin, מאזן בין מחיר ליכולות ניקוי קרקעית ודפנות.',ARRAY['חברה ישראלית עם שירות מקומי','איזון טוב בין מחיר ליכולת'],ARRAY['ללא ניקוי קו מים מלא כמו הדגמים המתקדמים'],'{"ניקוי":"קרקעית ודפנות"}','published','נקודת איזון טובה בקו Dolphin בין מחיר לביצועים.',ARRAY['בריכות ביתיות בינוניות'],ARRAY['בריכות גדולות ומורכבות'],ARRAY['israeli','value'],ARRAY['pool-cleaners']),
('aquabot-breeze-4wd','Aquabot Breeze 4WD','Aquabot',(select id from categories where slug='pool-cleaners'),7.8,'רובוט בריכה אלחוטי עם הנעת 4WD, ממותג אמריקאי ותיק בתחום.',ARRAY['אלחוטי עם הנעת 4WD','מתאים גם לבריכות אגן (above-ground)'],ARRAY['זמן ריצה מוגבל בסוללה'],'{"חשמל":"סוללה נטענת","הנעה":"4WD"}','published','אופציה אלחוטית טובה שמתאימה גם לבריכות אגן, לא רק בריכות בנויות.',ARRAY['בריכות אגן (above-ground)'],ARRAY['בריכות גדולות מאוד'],ARRAY['cordless'],ARRAY['pool-cleaners']),
('dolphin-premier','Dolphin Premier','Maytronics',(select id from categories where slug='pool-cleaners'),8.7,'דגם פרימיום נוסף של מייטרוניקס עם מערכת סינון רב-שכבתית לשליטה מדויקת בסוג הלכלוך.',ARRAY['סינון רב-שכבתי לפי סוג לכלוך','חברה ישראלית עם שירות מקיף'],ARRAY['מחיר גבוה'],'{"סינון":"רב-שכבתי מתחלף","ניקוי":"קרקעית, דפנות וקו מים"}','published','שליטה מדויקת בסוג הסינון, לבריכות עם סוגי לכלוך משתנים.',ARRAY['בריכות עם עלים וחול משתנים לפי עונה'],ARRAY['תקציב מוגבל'],ARRAY['israeli','premium'],ARRAY['pool-cleaners']),
('beatbot-aquasense-pro','Beatbot AquaSense Pro','Beatbot',(select id from categories where slug='pool-cleaners'),8.1,'גרסה נגישה יותר של קו AquaSense, עם ניקוי קרקעית ודפנות אלחוטי.',ARRAY['אלחוטי לגמרי','מחיר נמוך יותר מדגם ה-2'],ARRAY['ללא ניקוי פני מים כמו הדגם המתקדם'],'{"ניקוי":"קרקעית ודפנות","חשמל":"סוללה נטענת"}','published','רוב היתרונות האלחוטיים של Beatbot במחיר נגיש יותר.',ARRAY['בריכות בינוניות בלי גישה נוחה לחשמל'],ARRAY['בריכות עם הרבה עלים צפים'],ARRAY['cordless','value'],ARRAY['pool-cleaners'])
on conflict (slug) do nothing;

-- ===================== window-cleaners (9) =====================
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('hobot-388','Hobot 388','Hobot',(select id from categories where slug='window-cleaners'),8.4,'רובוט ניקוי חלונות עם שאיבת ואקום להיצמדות לזכוכית ומערכת ריסוס מים משולבת.',ARRAY['ואקום חזק להיצמדות בטוחה לזכוכית','מערכת ריסוס מים מובנית'],ARRAY['רעש שאיבת הוואקום ניכר יחסית'],'{"היצמדות":"שאיבת ואקום","ריסוס":"מים מובנה"}','published','אחד המותגים הוותיקים והמוכרים ביותר בקטגוריית רובוטי החלונות.',ARRAY['חלונות גדולים וקירות זכוכית'],ARRAY['מי שרגיש לרעש שאיבה'],ARRAY['established'],ARRAY['window-cleaners']),
('hobot-298','Hobot 298','Hobot',(select id from categories where slug='window-cleaners'),8.0,'דגם ביניים בקו Hobot, מאזן בין מחיר ליכולות ניקוי.',ARRAY['מחיר נגיש יותר מדגם 388','ניווט אוטומטי יעיל'],ARRAY['פחות תכונות מתקדמות מהדגל'],'{"היצמדות":"שאיבת ואקום"}','published','נקודת איזון טובה בקו Hobot למי שלא צריך את כל התכונות.',ARRAY['חלונות בגודל בינוני'],ARRAY['חלונות מאוד גדולים'],ARRAY['value'],ARRAY['window-cleaners']),
('ecovacs-winbot-w2-pro','Ecovacs Winbot W2 Pro','Ecovacs',(select id from categories where slug='window-cleaners'),8.5,'רובוט חלונות מבית Ecovacs עם ניווט חכם ובקרת נתיב מדויקת יותר מדגמים בסיסיים.',ARRAY['ניווט חכם עם נתיב ניקוי יעיל','מותג מוכר עם תמיכה'],ARRAY['מחיר גבוה יחסית לקטגוריה'],'{"היצמדות":"שאיבת ואקום","ניווט":"נתיב חכם"}','published','ניווט חכם ואמינות מותג עבור חלונות וקירות זכוכית גדולים.',ARRAY['קירות זכוכית גדולים בבתים גבוהים'],ARRAY['תקציב מוגבל'],ARRAY['smart-nav'],ARRAY['window-cleaners']),
('ecovacs-winbot-x','Ecovacs Winbot X','Ecovacs',(select id from categories where slug='window-cleaners'),8.7,'דגל Ecovacs לניקוי חלונות, עם משאבת ריק כפולה לבטיחות גבוהה יותר בגובה.',ARRAY['משאבת ריק כפולה לבטיחות מוגברת','מתאים גם למסגרות חלון ללא שפה'],ARRAY['מחיר מהגבוהים בקטגוריה'],'{"היצמדות":"משאבת ריק כפולה"}','published','הבטיחות הגבוהה ביותר בקטגוריה בזכות מערכת הריק הכפולה, חשוב במיוחד לקומות גבוהות.',ARRAY['חלונות בקומות גבוהות'],ARRAY['תקציב מוגבל'],ARRAY['premium','safety'],ARRAY['window-cleaners']),
('alfawise-s60','Alfawise S60','Alfawise',(select id from categories where slug='window-cleaners'),7.2,'רובוט חלונות תקציבי עם ניקוי אוטומטי בסיסי, פופולרי בזכות מחירו הנמוך.',ARRAY['מחיר נמוך משמעותית מהמותגים המובילים','חוט גיבוי בטיחותי כלול'],ARRAY['ביצועי ניווט בסיסיים יותר'],'{"היצמדות":"שאיבת ואקום","בטיחות":"חוט גיבוי כלול"}','published','אופציה תקציבית מאוד לחלון ביתי רגיל, לא לקירות זכוכית גדולים.',ARRAY['חלונות ביתיים בגודל רגיל'],ARRAY['קירות זכוכית מסחריים גדולים'],ARRAY['budget'],ARRAY['window-cleaners']),
('liectroux-x6','Liectroux X6','Liectroux',(select id from categories where slug='window-cleaners'),7.4,'רובוט חלונות עם ניתוב אוטומטי ומצלמה לזיהוי מסגרת החלון.',ARRAY['מצלמה לזיהוי מסגרת החלון','מחיר תחרותי'],ARRAY['מותג פחות מוכר בישראל'],'{"היצמדות":"שאיבת ואקום","ניווט":"מצלמה לזיהוי מסגרת"}','published','ניקוי חכם יחסית במחיר נגיש, למי שמוכן לוותר על מותג מוביל.',ARRAY['תקציב מוגבל'],ARRAY['מי שרוצה שירות מותג מוכר בישראל'],ARRAY['value'],ARRAY['window-cleaners']),
('cecotec-conga-winclean-990','Cecotec Conga WinClean 990','Cecotec',(select id from categories where slug='window-cleaners'),7.1,'רובוט חלונות ספרדי במחיר נגיש, עם ריסוס מים מובנה.',ARRAY['מחיר נמוך','ריסוס מים מובנה'],ARRAY['תמיכה ושירות בישראל מוגבלים'],'{"היצמדות":"שאיבת ואקום","ריסוס":"מים מובנה"}','published','אופציה תקציבית נוספת לחלון ביתי רגיל.',ARRAY['תקציב נמוך מאוד'],ARRAY['קירות זכוכית גדולים ומורכבים'],ARRAY['budget'],ARRAY['window-cleaners']),
('hobot-legee-8','Hobot Legee 8','Hobot',(select id from categories where slug='window-cleaners'),8.6,'הדגל העדכני של Hobot, עם מיפוי החלון ותכנון נתיב חכם לפני תחילת הניקוי.',ARRAY['מיפוי החלון לפני ניקוי לנתיב יעיל','מהיר ביחס לדגמים קודמים'],ARRAY['מחיר גבוה'],'{"ניווט":"מיפוי חכם לפני ניקוי","היצמדות":"שאיבת ואקום"}','published','הדגם המתקדם ביותר של Hobot, למי שרוצה ניקוי מהיר ומדויק.',ARRAY['חלונות וקירות זכוכית גדולים'],ARRAY['תקציב מוגבל'],ARRAY['flagship'],ARRAY['window-cleaners']),
('liectroux-win-corner','Liectroux Win Corner','Liectroux',(select id from categories where slug='window-cleaners'),7.0,'רובוט חלונות עם דגש על הגעה לפינות בעזרת עיצוב קצוות ייעודי.',ARRAY['עיצוב קצוות שמגיע טוב יותר לפינות','מחיר נגיש'],ARRAY['ביצועים בסיסיים על חלונות גדולים מאוד'],'{"עיצוב":"קצוות מותאמים לפינות"}','published','טוב במיוחד לחלונות עם הרבה פינות ומסגרות מפוצלות.',ARRAY['חלונות מרובי-משבצות'],ARRAY['קירות זכוכית גדולים אחידים'],ARRAY['budget'],ARRAY['window-cleaners'])
on conflict (slug) do nothing;
