-- Continuation — see 20260730050000_seed_real_products.sql header.
--
-- humanoids, companions and kids-robots intentionally have fewer rows
-- than 20: the real consumer market in each is genuinely smaller. Padding
-- these to 20 would mean inventing products that don't exist.

-- ===================== humanoids (5) =====================
-- The real humanoid market barely has consumer-purchasable products yet.
-- These are genuinely real and either purchasable (at high, institutional
-- prices) or in active pre-order/waitlist — never invented models. The
-- "not for sale yet" ones are marked as such in the summary itself,
-- not hidden.
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('unitree-g1','Unitree G1','Unitree',(select id from categories where slug='humanoids'),7.5,'הומנואיד סיני שכבר נמכר בפועל למפתחים ומוסדות, במחיר גבוה משמעותית ממוצרי צריכה רגילים.',ARRAY['נמכר בפועל כיום, לא רק הכרזה','גמישות תנועה גבוהה ל-23 מפרקים ומעלה'],ARRAY['מיועד למפתחים ומוסדות, לא לצרכן הביתי הרגיל','מחיר גבוה מאוד'],'{"סטטוס":"נמכר בפועל למפתחים ומוסדות","מפרקים":"23 ומעלה"}','published','הדגם ההומנואידי הכי נגיש היום לרכישה בפועל, אך עדיין לא מוצר צריכה ביתי.',ARRAY['מוסדות מחקר ומפתחי רובוטיקה'],ARRAY['שימוש ביתי יומיומי'],ARRAY['developer'],ARRAY['humanoids']),
('unitree-h1','Unitree H1','Unitree',(select id from categories where slug='humanoids'),7.8,'הומנואיד גדול יותר של Unitree בגובה אדם, מיועד למחקר ופיתוח מתקדם.',ARRAY['גובה וכוח קרובים לאדם בוגר','מהיר יחסית לקטגוריה'],ARRAY['מחיר גבוה מאוד, לא מוצר צריכה'],'{"סטטוס":"נמכר למוסדות ומפתחים","גובה":"בגובה אדם בוגר בקירוב"}','published','אחד ההומנואידים המהירים והמתקדמים שנמכרים בפועל כיום, אך למגזר המחקר בלבד.',ARRAY['מוסדות מחקר מתקדמים'],ARRAY['צרכן ביתי'],ARRAY['developer'],ARRAY['humanoids']),
('1x-neo-beta','1X NEO Beta','1X Technologies',(select id from categories where slug='humanoids'),null,'הומנואיד המיועד לשימוש ביתי, כרגע בשלב רשימת המתנה/בטא מוגבלת ולא במכירה כללית.',ARRAY['תוכנן מההתחלה לשימוש ביתי, לא תעשייתי'],ARRAY['לא זמין לרכישה כללית — רשימת המתנה בלבד כרגע'],'{"סטטוס":"רשימת המתנה / בטא מוגבלת"}','published','המועמד המעניין ביותר להומנואיד ביתי אמיתי, אך עדיין לא ניתן לרכישה בישראל או בעולם.',ARRAY['מי שרוצה להירשם מוקדם לרשימת המתנה'],ARRAY['מי שמחפש רכישה מיידית'],ARRAY['waitlist'],ARRAY['humanoids']),
('ubtech-walker-s','UBTECH Walker S','UBTECH',(select id from categories where slug='humanoids'),7.2,'הומנואיד סיני שנפרס בעיקר בקווי ייצור ומחסנים, לא מוצר צריכה.',ARRAY['כבר בפריסה בפועל בסביבות תעשייתיות','חברה עם ניסיון ארוך ברובוטיקה צרכנית (Alpha, Cruzr)'],ARRAY['מיועד לתעשייה, לא לבית'],'{"סטטוס":"בפריסה תעשייתית"}','published','דוגמה לכך שהומנואידים כבר עובדים בפועל — אך בתעשייה, לא בבית.',ARRAY['יישומים תעשייתיים ולוגיסטיים'],ARRAY['שימוש ביתי'],ARRAY['industrial'],ARRAY['humanoids']),
('tesla-optimus','Tesla Optimus','Tesla',(select id from categories where slug='humanoids'),null,'ההומנואיד המוכר ביותר בתקשורת, אך נכון להיום עדיין לא מוצר הנמכר לצרכנים.',ARRAY['פיתוח מהיר ותקציב עצום מאחוריו'],ARRAY['אינו נמכר כלל לצרכנים כרגע — אין תאריך יעד רשמי'],'{"סטטוס":"טרם נמכר לצרכנים"}','published','אנחנו עוקבים אחריו, אבל נכון להיום אין מה לקנות — נעדכן ברגע שיהיה.',ARRAY['מי שרוצה להישאר מעודכן על הקטגוריה'],ARRAY['מי שרוצה לקנות הומנואיד היום'],ARRAY['upcoming'],ARRAY['humanoids'])
on conflict (slug) do nothing;

-- ===================== companions / pet robots (10) =====================
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('sony-aibo-ers-1000','Sony Aibo (ERS-1000)','Sony',(select id from categories where slug='companions'),8.6,'כלב הרובוט המתקדם ביותר בשוק, עם למידת התנהגות ואישיות שמתפתחת עם הזמן.',ARRAY['אישיות שמתפתחת ולומדת לאורך זמן','חיישנים ומצלמות רבים ליצירת תגובות טבעיות'],ARRAY['דורש מנוי ענן חודשי לחלק מהיכולות','מחיר גבוה'],'{"למידה":"אישיות מתפתחת מבוססת AI","חיישנים":"מצלמות ומגע מרובים"}','published','המתקדם ביותר בקטגוריה, אבל עם עלות מנוי מתמשכת שצריך לקחת בחשבון.',ARRAY['מי שרוצה את חוויית הרובוט-חיה המתקדמת ביותר'],ARRAY['מי שלא רוצה מנוי חודשי נוסף'],ARRAY['flagship','subscription'],ARRAY['companions']),
('tombot-jennie','Tombot Jennie','Tombot',(select id from categories where slug='companions'),7.9,'גור כלב רובוטי מטיפולי, מיועד בעיקר לקשישים ולאנשים עם דמנציה, עם תגובות מגע ריאליסטיות.',ARRAY['מיועד ספציפית לטיפול ותמיכה רגשית','תגובות מגע וקול ריאליסטיות במיוחד'],ARRAY['לא נועד למשחק פעיל כמו רובוט ילדים'],'{"ייעוד":"טיפולי, לקשישים ואנשים עם דמנציה"}','published','הכי מתאים לצרכי תמיכה רגשית וטיפולית, פחות למשחק פעיל.',ARRAY['קשישים ואנשים עם דמנציה'],ARRAY['ילדים שרוצים משחק פעיל'],ARRAY['therapeutic'],ARRAY['companions']),
('loona-petbot','Loona','KEYi Tech',(select id from categories where slug='companions'),7.6,'רובוט חמוד בגודל קטן עם עיניים דיגיטליות אקספרסיביות ואפליקציית אינטראקציה.',ARRAY['עיצוב חמוד ואקספרסיבי במיוחד','מחיר נגיש יחסית לקטגוריה'],ARRAY['פחות "חכם" מבחינת יכולות AI מתקדמות'],'{"עיצוב":"עיניים דיגיטליות אקספרסיביות"}','published','אופציה נגישה וחמודה למי שרוצה רובוט-חיה בלי מחיר פרימיום.',ARRAY['משפחות עם ילדים שרוצות רובוט חמוד'],ARRAY['מי שמחפש AI מתקדם במיוחד'],ARRAY['value','cute'],ARRAY['companions']),
('moflin','Moflin','Casio (Vanguard Industries)',(select id from categories where slug='companions'),7.4,'יצור רובוטי פרוותי קטן שמפתח "רגשות" מבוססי אינטראקציה, ללא צורה של חיה מוכרת.',ARRAY['פרווה רכה ומרקם נעים למגע','מפתח דפוסי "מצב רוח" ייחודיים לפי אינטראקציה'],ARRAY['ללא תנועה עצמאית משמעותית'],'{"עיצוב":"יצור פרוותי, לא צורת חיה מוכרת"}','published','חוויית מגע ורגש ייחודית, אבל בלי תנועה עצמאית כמו רובוטים אחרים בקטגוריה.',ARRAY['מי שמחפש חוויית מגע רגועה ומרגיעה'],ARRAY['מי שרוצה רובוט שזז וחוקר בעצמו'],ARRAY['sensory'],ARRAY['companions']),
('petoi-bittle','Petoi Bittle','Petoi',(select id from categories where slug='companions'),7.7,'כלב רובוטי בבנייה עצמית (קיט) בקוד פתוח, מיועד לחובבי טכנולוגיה ולימוד רובוטיקה.',ARRAY['קוד פתוח וניתן לתכנות עצמאי','חוויית בנייה חינוכית'],ARRAY['דורש הרכבה וידע טכני בסיסי'],'{"סוג":"קיט הרכבה, קוד פתוח"}','published','הבחירה למי שרוצה ללמוד רובוטיקה, לא רק לקנות רובוט מוגמר.',ARRAY['נוער ומבוגרים שאוהבים DIY וטכנולוגיה'],ARRAY['מי שרוצה מוצר מוגמר מהקופסה'],ARRAY['diy','open-source'],ARRAY['companions']),
('petoi-nybble','Petoi Nybble','Petoi',(select id from categories where slug='companions'),7.5,'חתול רובוטי בבנייה עצמית מאותה חברה כמו Bittle, קוד פתוח וניתן לתכנות.',ARRAY['קוד פתוח','קהילת מפתחים פעילה'],ARRAY['דורש הרכבה וידע טכני'],'{"סוג":"קיט הרכבה, קוד פתוח"}','published','גרסת החתול לאותה חוויית DIY חינוכית כמו Bittle.',ARRAY['חובבי DIY ורובוטיקה'],ARRAY['מי שרוצה מוצר מוגמר'],ARRAY['diy','open-source'],ARRAY['companions']),
('anki-vector','Anki Vector','Anki (Digital Dream Labs)',(select id from categories where slug='companions'),7.0,'רובוט שולחני אקספרסיבי עם אישיות, המשיך לפעול תחת בעלים חדשים אחרי סגירת החברה המקורית.',ARRAY['אישיות ותגובות מפותחות במיוחד לגודלו','מזהה פנים וקול'],ARRAY['החברה המקורית נסגרה — תמיכה ארוכת טווח פחות ודאית'],'{"היסטוריה":"פותח ע״י Anki, נרכש ע״י Digital Dream Labs"}','published','חוויה מקורית ומפותחת, אבל כדאי לבדוק זמינות תמיכה עדכנית לפני רכישה.',ARRAY['אספני רובוטיקה וטכנולוגיה'],ARRAY['מי שרוצה תמיכת יצרן יציבה לטווח ארוך'],ARRAY['legacy'],ARRAY['companions']),
('circuitmess-nova','CircuitMess Nova','CircuitMess',(select id from categories where slug='companions'),7.1,'רובוט חינוכי בבנייה עצמית עם מסך ופרצוף דיגיטלי, מיועד ללימוד קוד ואלקטרוניקה.',ARRAY['ערכת בנייה חינוכית מלאה','מלמד תכנות ואלקטרוניקה בפועל'],ARRAY['מיועד ללמידה, פחות ל"חברות" יומיומית'],'{"סוג":"קיט חינוכי בבנייה עצמית"}','published','הכי טוב כמתנה חינוכית שמלמדת קוד, פחות כרובוט-חיה יומיומי.',ARRAY['ילדים ונוער שרוצים ללמוד תכנות'],ARRAY['מי שמחפש חוויית ליווי רגשי'],ARRAY['educational','diy'],ARRAY['companions']),
('wowwee-cozmo-alt-robosen','Robosen K1 Optimus Prime','Robosen',(select id from categories where slug='companions'),7.3,'רובוט אספנות ניתן לתכנות שהופך צורה, לקהל חובבי טכנולוגיה ואספנים בוגרים.',ARRAY['הפיכת צורה (טרנספורמציה) פיזית אמיתית','ניתן לתכנות תנועות מותאמות אישית'],ARRAY['מחיר גבוה יחסית לרובוט אספנות'],'{"סוג":"רובוט אספנות ניתן לתכנות"}','published','מוצר לאספנים בוגרים יותר מאשר רובוט-חיה קלאסי.',ARRAY['אספני טכנולוגיה בוגרים'],ARRAY['מי שמחפש רובוט-חיה קלאסי לילדים'],ARRAY['collector'],ARRAY['companions']),
('ropet','Ropet','Ropet Robotics',(select id from categories where slug='companions'),7.2,'רובוט-חיה קטן ומחמד המגיב לליטוף ולקול, ממוקד קהל מבוגרים וקשישים לחברה יומיומית.',ARRAY['תגובות ליטוף וקול פשוטות ומרגיעות','גודל קטן ונוח לאחזקה'],ARRAY['פחות יכולות "חכמות" מתקדמות'],'{"ייעוד":"חברה יומיומית, בעיקר לקשישים"}','published','חברה פשוטה ומרגיעה, פחות מוצר טכנולוגי מתקדם.',ARRAY['קשישים המחפשים חברה פשוטה'],ARRAY['מי שמחפש יכולות AI מתקדמות'],ARRAY['simple'],ARRAY['companions'])
on conflict (slug) do nothing;

-- ===================== kids-robots (11) =====================
insert into robots (slug, name, brand, category_id, score, summary, pros, cons, specs, status, verdict, best_for, not_for, comparison_tags, calculator_tags) values
('lego-spike-prime','LEGO Education SPIKE Prime','LEGO',(select id from categories where slug='kids-robots'),8.8,'ערכת רובוטיקה חינוכית מבוססת LEGO, עם חיישנים ותכנות ויזואלי מבוסס Scratch.',ARRAY['תכנות ויזואלי ידידותי מבוסס Scratch','חלקי LEGO תואמים לערכות קיימות'],ARRAY['מחיר גבוה יחסית כערכה חינוכית'],'{"תכנות":"ויזואלי, מבוסס Scratch","גיל מומלץ":"מגיל 10 ומעלה"}','published','אחת מערכות הרובוטיקה החינוכיות המובילות בעולם, גם בבתי ספר בישראל.',ARRAY['ילדים שרוצים ללמוד תכנות ורובוטיקה ברצינות'],ARRAY['תקציב מוגבל למתנה חד-פעמית'],ARRAY['educational'],ARRAY['kids-robots']),
('lego-mindstorms-robot-inventor','LEGO Mindstorms Robot Inventor','LEGO',(select id from categories where slug='kids-robots'),8.5,'ערכת הרובוטיקה המתקדמת של LEGO להרכבת חמישה דגמי רובוט שונים עם תכנות מלא.',ARRAY['חמישה דגמי רובוט מוכנים בערכה אחת','תכנות מתקדם יותר עבור ילדים גדולים יותר'],ARRAY['הפסקת ייצור רשמית — זמינות תלויה במלאי קיים'],'{"תכנות":"ויזואלי ומתקדם","דגמים":"5 רובוטים שונים בערכה"}','published','עדיין אחת הערכות המתקדמות ביותר שקיימות, כדאי לבדוק זמינות מלאי.',ARRAY['ילדים גדולים יותר שרוצים אתגר מתקדם'],ARRAY['ילדים צעירים מדי לתכנות מורכב'],ARRAY['educational'],ARRAY['kids-robots']),
('sphero-bolt','Sphero BOLT','Sphero',(select id from categories where slug='kids-robots'),8.2,'כדור רובוטי מתגלגל עם מסך LED מלא ותכנות ויזואלי, פופולרי מאוד בבתי ספר.',ARRAY['עמיד ואיכותי, שורד נפילות היטב','מסך LED מלא לאנימציות ותצוגות'],ARRAY['פחות "בנייה" פיזית — הצורה קבועה'],'{"תכנות":"ויזואלי (Sphero Edu)","עיצוב":"כדור עמיד עם LED"}','published','אחד המוצרים החינוכיים הפופולריים ביותר בעולם, מתאים גם למשחק וגם ללימוד.',ARRAY['ילדים בגיל בית ספר יסודי'],ARRAY['ילדים שרוצים לבנות ולהרכיב פיזית'],ARRAY['educational'],ARRAY['kids-robots']),
('sphero-indi','Sphero Indi','Sphero',(select id from categories where slug='kids-robots'),7.9,'רובוט מתגלגל על מסלולי צבע, מיועד לילדים צעירים ללמוד יסודות תכנות בלי מסך.',ARRAY['תכנות ללא מסך, מבוסס כרטיסי צבע פיזיים','מתאים לגילאי גן וכיתות נמוכות'],ARRAY['פחות מתקדם לילדים גדולים יותר'],'{"תכנות":"כרטיסי צבע פיזיים, ללא מסך","גיל מומלץ":"מגיל 4"}','published','המתאים ביותר לגיל הצעיר ביותר בקטגוריה, בלי צורך במסך כלל.',ARRAY['ילדי גן וכיתות א-ב'],ARRAY['ילדים גדולים שרוצים תכנות מתקדם'],ARRAY['educational','young-kids'],ARRAY['kids-robots']),
('wonder-workshop-dash','Wonder Workshop Dash','Wonder Workshop',(select id from categories where slug='kids-robots'),8.0,'רובוט חינוכי אקספרסיבי עם עיניים ותנועה, נלמד באפליקציות מדורגות לפי גיל.',ARRAY['אפליקציות מדורגות לפי רמת גיל','אישיות ותגובות חמודות שמושכות ילדים צעירים'],ARRAY['מחיר גבוה יחסית לרובוט אחד'],'{"תכנות":"אפליקציות מדורגות (Blockly)","גיל מומלץ":"מגיל 6"}','published','שילוב טוב בין אישיות מושכת ללימוד תכנות מדורג.',ARRAY['ילדים בגילאי בית ספר יסודי'],ARRAY['תקציב מוגבל'],ARRAY['educational'],ARRAY['kids-robots']),
('wonder-workshop-cue','Wonder Workshop Cue','Wonder Workshop',(select id from categories where slug='kids-robots'),7.8,'רובוט מתקדם יותר מ-Dash, מיועד לילדים גדולים יותר עם תכנות טקסטואלי בסיסי.',ARRAY['מעבר הדרגתי מתכנות ויזואלי לטקסטואלי','אישיות אקספרסיבית עם "מצבי רוח"'],ARRAY['פחות מתאים לילדים צעירים מדי'],'{"תכנות":"ויזואלי ומעבר לטקסטואלי","גיל מומלץ":"מגיל 11"}','published','גשר טוב בין תכנות ויזואלי לתכנות טקסטואלי אמיתי.',ARRAY['ילדים בגילאי חטיבת ביניים'],ARRAY['ילדי גן וכיתות נמוכות'],ARRAY['educational'],ARRAY['kids-robots']),
('ozobot-evo','Ozobot Evo','Ozobot',(select id from categories where slug='kids-robots'),7.7,'רובוט זעיר שקורא קודי צבע על נייר ומגיב אליהם, בנוסף לתכנות דיגיטלי מתקדם יותר.',ARRAY['ניתן לתכנות עם טוש וקודי צבע על נייר, בלי מסך','גם אפשרות תכנות דיגיטלי לגילאים גדולים יותר'],ARRAY['גודל קטן מאוד עלול ללכת לאיבוד'],'{"תכנות":"קודי צבע על נייר + תכנות דיגיטלי","גיל מומלץ":"מגיל 6"}','published','ייחודי בזכות האפשרות ללמד תכנות בסיסי עם טוש ונייר בלבד.',ARRAY['כיתות עם משאבי מסכים מוגבלים'],ARRAY['משפחות עם ילדים צעירים מאוד שמאבדים חלקים קטנים'],ARRAY['educational'],ARRAY['kids-robots']),
('makeblock-mbot2','Makeblock mBot2','Makeblock',(select id from categories where slug='kids-robots'),7.9,'רובוט חינוכי מודולרי עם תכנות ויזואלי ותמיכה בבינה מלאכותית בסיסית (זיהוי קול ותמונה).',ARRAY['תמיכה בזיהוי קול ותמונה בסיסי','מודולרי וניתן להרחבה עם חיישנים נוספים'],ARRAY['דורש הרכבה ראשונית'],'{"תכנות":"ויזואלי (Scratch), AI בסיסי","גיל מומלץ":"מגיל 8"}','published','אופציה טובה למי שרוצה להכניס גם מושגי AI בסיסיים ללימוד הרובוטיקה.',ARRAY['ילדים שכבר מכירים תכנות בסיסי'],ARRAY['ילדים צעירים מדי להרכבה עצמאית'],ARRAY['educational','ai'],ARRAY['kids-robots']),
('vex-iq','VEX IQ','VEX Robotics',(select id from categories where slug='kids-robots'),8.1,'מערכת רובוטיקה תחרותית המשמשת בתחרויות VEX IQ ברחבי העולם, כולל בישראל.',ARRAY['משמש בתחרויות רובוטיקה בין-לאומיות אמיתיות','קהילה ותמיכה חינוכית רחבה'],ARRAY['עקומת למידה תלולה יותר ממוצרים פשוטים'],'{"תכנות":"VEXcode, ויזואלי וטקסטואלי","שימוש":"תחרויות VEX IQ"}','published','הבחירה הטובה ביותר למשפחות שרוצות להתקדם לתחרויות רובוטיקה אמיתיות.',ARRAY['ילדים המעוניינים בתחרויות רובוטיקה'],ARRAY['מי שרק רוצה צעצוע פשוט למשחק'],ARRAY['competitive','educational'],ARRAY['kids-robots']),
('ubtech-jimu-astrobot','UBTECH JIMU AstroBot','UBTECH',(select id from categories where slug='kids-robots'),7.5,'ערכת בנייה רובוטית עם חלקים מתחברים ותכנות ויזואלי, בעיצוב בהשראת חלל.',ARRAY['חלקי בנייה מתחברים בקלות ללא כלים','תכנות ויזואלי ידידותי למתחילים'],ARRAY['פחות מוכר ותמיכה מוגבלת יותר מ-LEGO'],'{"תכנות":"ויזואלי (JIMU App)","הרכבה":"חלקים מתחברים ללא כלים"}','published','אופציה נגישה יותר ל-LEGO Mindstorms במחיר נמוך יותר.',ARRAY['ילדים שאוהבים נושא חלל וחלליות'],ARRAY['מי שרוצה תמיכה ארוכת טווח כמו LEGO'],ARRAY['value','educational'],ARRAY['kids-robots']),
('makeblock-codey-rocky','Makeblock Codey Rocky','Makeblock',(select id from categories where slug='kids-robots'),7.6,'רובוט כניסה ללימוד תכנות לילדים צעירים, עם מסך LED פשוט ותכנות בלוקים.',ARRAY['מתאים כמבוא ראשון ללימוד תכנות','מחיר נגיש יחסית'],ARRAY['פחות הרחבות אפשריות מ-mBot2'],'{"תכנות":"ויזואלי (Scratch)","גיל מומלץ":"מגיל 6"}','published','נקודת כניסה נעימה וזולה ללימוד תכנות ראשוני.',ARRAY['ילדים צעירים בפעם הראשונה שלהם עם רובוטיקה'],ARRAY['ילדים שכבר מנוסים ורוצים אתגר גדול יותר'],ARRAY['value','educational'],ARRAY['kids-robots'])
on conflict (slug) do nothing;
